### ISSUE TITLE
Project not compiling

### ISSUE THREAD

**Issue by ekstazas** [danielkrupinski/GOESP#102]
When I try to compile it, I get 7 errors: 

Severity	Code	Description	Project	File	Line	Suppression State

Error	C2039	'sort': is not a member of 'std::ranges'	GOESP	C:\Users\rt\Downloads\GOESP-master\GOESP\Hacks\Misc.cpp	LINE: 632	

Message		see declaration of 'std::ranges'	GOESP	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\algorithm	LINE: 1269	

Error	C2672	'sort': no matching overloaded function found	GOESP	C:\Users\rt\Downloads\GOESP-master\GOESP\Hacks\Misc.cpp	LINE: 632	

Error	C2780	'void std::sort(_ExPo &&,const _RanIt,const _RanIt) noexcept': expects 3 arguments - 2 provided	GOESP	C:\Users\rt\Downloads\GOESP-master\GOESP\Hacks\Misc.cpp	LINE: 638	

Message		see declaration of 'std::sort'	GOESP	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\algorithm	LINE: 4366	

Error	C2780	'void std::sort(_ExPo &&,_RanIt,_RanIt,_Pr) noexcept': expects 4 arguments - 2 provided	GOESP	C:\Users\rt\Downloads\GOESP-master\GOESP\Hacks\Misc.cpp	LINE: 638	

Message		see declaration of 'std::sort'	GOESP	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\algorithm	LINE: 4363	

Error	C2782	'void std::sort(const _RanIt,const _RanIt)': template parameter '_RanIt' is ambiguous	GOESP	C:\Users\rt\Downloads\GOESP-master\GOESP\Hacks\Misc.cpp	LINE: 638	

Message		see declaration of 'std::sort'	GOESP	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\algorithm	LINE: 4357	

Message		could be 'drawPlayerList::<lambda_1>'	GOESP	C:\Users\rt\Downloads\GOESP-master\GOESP\Hacks\Misc.cpp	LINE: 638	

Message		or       'std::vector<std::reference_wrapper<const PlayerData>,std::allocator<std::reference_wrapper<const PlayerData>>>'	GOESP	C:\Users\rt\Downloads\GOESP-master\GOESP\Hacks\Misc.cpp	LINE: 638	

Error	C2784	'void std::sort(const _RanIt,const _RanIt)': could not deduce template argument for 'const _RanIt' from 'drawPlayerList::<lambda_1>'	GOESP	C:\Users\rt\Downloads\GOESP-master\GOESP\Hacks\Misc.cpp	LINE: 638	

Message		see declaration of 'std::sort'	GOESP	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\algorithm	LINE: 4357	

Error	C2780	'void std::sort(const _RanIt,const _RanIt,_Pr)': expects 3 arguments - 2 provided	GOESP	C:\Users\rt\Downloads\GOESP-master\GOESP\Hacks\Misc.cpp	LINE: 638	

Message		see declaration of 'std::sort'	GOESP	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.26.28801\include\algorithm	LINE: 4349	

Any help or suggestions on how to get it working?

**Comment by danielkrupinski** [comment]
Update Visual Studio.
