### ISSUE TITLE
How to inject this in linux?

### ISSUE THREAD

**Issue by thevendigo** [danielkrupinski/GOESP#104]
I have Manjaro with cathook's gdb

**Comment by thevendigo** [comment]
I have Manjaro with cathook's gdb

**Comment by danielkrupinski** [comment]
Execute `sudo gdb -batch-silent -p $(pidof csgo_linux64) -ex "call (void*)__libc_dlopen_mode(\"$PWD/libGOESP.so\", 2)"` in a directory containing **libGOESP.so**

**Comment by tar420** [comment]
**thank you!**
