### ISSUE TITLE
Compile Failed

### ISSUE THREAD

**Issue by iPurya** [danielkrupinski/GOESP#105]
Hi,
![image](https://user-images.githubusercontent.com/58905883/114762182-b39c5180-9d76-11eb-8948-915e38ce0121.png)

**Comment by danielkrupinski** [comment]
Scroll up and show the error message.

**Comment by iPurya** [comment]
![image](https://user-images.githubusercontent.com/58905883/114788995-aba0d980-9d97-11eb-9903-840d8ea9c15c.png)

**Comment by danielkrupinski** [comment]
Update Visual Studio.
