### ISSUE TITLE
BUG: issue with "make -j $(nproc --all)"

### ISSUE THREAD

**Issue by qwertzon** [danielkrupinski/GOESP#114]
/home/qwertzon/GOESP/GOESP/pch.h:3:10: fatal error: intrin.h: No such file or directory
    3 | #include <intrin.h>
      |          ^~~~~~~~~~

and lots of errors lead after that

Im using ubuntu budgie and have installed dependencies I have also installed g++.

**Comment by danielkrupinski** [comment]
Fixed
