### ISSUE TITLE
Please fix "????" symbols in Cyrillic cs go

### ISSUE THREAD

**Issue by playday3008** [danielkrupinski/GOESP#15]

**Comment by danielkrupinski** [comment]
Where are those symbols?

**Comment by playday3008** [comment]
2 minutes

**Comment by playday3008** [comment]
![image](https://user-images.githubusercontent.com/18056374/78302720-a467ae80-753b-11ea-8831-96a5e55110ec.png)

**Comment by danielkrupinski** [comment]
Just change the ESP font to one supporting Cyrillic glyphs.

**Comment by playday3008** [comment]
Okay, write this in README.md
