### ISSUE TITLE
esp- stream obs - 

### ISSUE THREAD

**Issue by TeknoproTV** [danielkrupinski/GOESP#18]
Hello dear brother, could you please add wallhack. thank you.

**Comment by TeknoproTV** [comment]
plaseeee

**Comment by techprimedev** [comment]
este è um ESP Hack, creio que voce deveria chamar isso de wallhack jà que voce consegue ve-los pelas paredes. lol

**Comment by techprimedev** [comment]
> este è um ESP Hack, creio que voce deveria chamar isso de wallhack jà que voce consegue ve-los pelas paredes. lol

Boom!

**Comment by danielkrupinski** [comment]
That's exactly what this project is.
