### ISSUE TITLE
[Suggestion] Stream Proof on discord stream

### ISSUE THREAD

**Issue by EGTLoneWolfz** [danielkrupinski/GOESP#21]
Can you make it so we can choice or switch abt which to hook?

**Comment by danielkrupinski** [comment]
You can select your overlay here https://github.com/danielkrupinski/GOESP/blob/08ba16d4233a7a5b6658b6bfcb7c36f15f902850/GOESP/Memory.cpp#L18

**Comment by EGTLoneWolfz** [comment]
changed but still visible on discord stream

**Comment by danielkrupinski** [comment]
I've tested this today and it's invisible on discord stream, doesn't matter which overlay you use for rendering.

**Comment by LvKafija** [comment]
Don't use screenshare, use only stream CSGO
