### ISSUE TITLE
Crash issues

### ISSUE THREAD

**Issue by LvKafija** [danielkrupinski/GOESP#24]
I have been getting crashes since start of the last month.

Have tried checking event viewer, reinstal windows, updating drivers etc. Everything that came in my mind this past month, but with no progress, after injecting, it allows to play 1-2 rounds and then crashes.
To be precise since 1. aprille update.

Checked Osiris project, but it doesn't crash.
Hope some one can help me to figure out.. where is the problem.

**Comment by danielkrupinski** [comment]
Should be fixed now (86c2fcc563207380930bbdc322108cc0d001f259). Thanks for reporting!

**Comment by LvKafija** [comment]
Checking, the new update.

**Comment by LvKafija** [comment]
Looks like bug has been fixed 👍
