### ISSUE TITLE
Bad FPS when moving mouse

### ISSUE THREAD

**Issue by gommefan6969** [danielkrupinski/GOESP#25]
Hello! Sorry for my fresh github account.
Well, after first testing the cheat, i noticed that my fps were really low and the cpu usage was really high while moving the mouse. (while ingame)
Normal FPS: 100-200
While slowly moving the mouse: 60-70
While quickly moving the mouse: 10-20, frozen
Due to my CPU not being that good (always 100% lol), i haven't noticed any cpu spikes in the task manager, although the gpu usage went down.
I tried the following things:
- fullscreen
- windowed
- discord overlay instead of steam
- local workshop map
- deathmatch

If you need it, i could record the issue.

Thank you,

**Comment by danielkrupinski** [comment]
A video would be useful. You can try to comment these two lines: https://github.com/danielkrupinski/GOESP/blob/86c2fcc563207380930bbdc322108cc0d001f259/GOESP/Hooks.cpp#L47-L48
and check if framerate has improved.

**Comment by danielkrupinski** [comment]
Check out 59d6729b70b4b98230364c12c156616354210bec and let me know if that resolves your issue.

**Comment by gommefan6969** [comment]
> A video would be useful. 
https://streamable.com/4nmckw


You can try to comment these two lines:
> 
> https://github.com/danielkrupinski/GOESP/blob/86c2fcc563207380930bbdc322108cc0d001f259/GOESP/Hooks.cpp#L47-L48
> 
> 
> and check if framerate has improved.

that fixed the framerate, yeah



> Check out [59d6729](https://github.com/danielkrupinski/GOESP/commit/59d6729b70b4b98230364c12c156616354210bec) and let me know if that resolves your issue.

will do

**Comment by gommefan6969** [comment]
> Check out [59d6729](https://github.com/danielkrupinski/GOESP/commit/59d6729b70b4b98230364c12c156616354210bec) and let me know if that resolves your issue.

works perfectly now, thank you :)
