### ISSUE TITLE
Cursor when opening menu in game.

### ISSUE THREAD

**Issue by VladimirKlitchsko** [danielkrupinski/GOESP#3]
This is not an issue but really a thread for help.

I have set the GOESP up in a way meaning when a key is pressed the menu opens and another key is pressed the menu is closed. However opening the menu this way means there is no cursor ingame unless you open the menu in the ESC menu. Which I don't want to do. How would I go around doing this so that the cursor shows ingame?

**Comment by danielkrupinski** [comment]
It was done like that to not hook any of game functions. I've found a way to unlock cursor, so menu will be toggleable in game.

**Comment by danielkrupinski** [comment]
You can now toggle GUI while in game by pressing `INSERT` key.
