### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by ChikyuTenshi** [danielkrupinski/GOESP#34]
Hey there~!

I'm having an issue while trying to compile this, when I try to compile the project it yields a DLL instead on and EXE

**Comment by oron-sinaa** [comment]
Oops! This does NOT build an exe, it builds a DLL which you'll have to INJECT into CSGO.EXE after running it. 
Use an available injector program or build your own if you've the knowledge.

**Comment by ChikyuTenshi** [comment]
That's my bad! Thanks It seems to be working flawlessly now~
