### ISSUE TITLE
Chams

### ISSUE THREAD

**Issue by avangersKinkyClient** [danielkrupinski/GOESP#35]
Hello mister ,
i did try to implement chams to the cheat and i can't get it to work i got errors like :
`Severity	Code	Description	Project	File	Line	Suppression State
Error	C2446	'==': no conversion from 'Material *const ' to 'int' (compiling source file Chams.cpp)	KinkyClient Free Dutchy Version	D:\visual studio 2019 projects\KinkyClient Free Dutchy Version\KinkyClient Free\GOESP\Chams.h	78`
how do i fix because i did implemet it in every file but not wanna work and another error : 
![image](https://user-images.githubusercontent.com/63201809/84309492-7a94be80-ab60-11ea-86ba-899bea1f9f31.png)
how to fix ?
regards avangers

**Comment by tirziz** [comment]
Just use Osiris

**Comment by avangersKinkyClient** [comment]
I make my own but i did download goesp for design i did remove all code and did write my own but i can't add chams

**Comment by danielkrupinski** [comment]
You haven't defined MaterialSystem class.
