### ISSUE TITLE
Fast Reload Progress

### ISSUE THREAD

**Issue by Hirashi3630** [danielkrupinski/GOESP#37]
Hi, there is this reload progress circle that shows duration of the reload animation.

**I was wondering if is possible to add something like this without manually finding values for each gun**:

![fast_reload_idea1](https://user-images.githubusercontent.com/37778278/84388300-a2cdfd00-abf4-11ea-9764-35b219470b19.png)
_yellow line indicate from when you can "fast reload" (switch to knife and back)_

## reload without fast reload
![reload_slow1](https://user-images.githubusercontent.com/37778278/84388654-3e5f6d80-abf5-11ea-9dcc-9814921a7bd9.gif)

## ideal fast reload
![reload_fast1](https://user-images.githubusercontent.com/37778278/84388652-3d2e4080-abf5-11ea-9585-9963cf2af91e.gif)

If you can redirect me or somehow help me it'd be awesome!

_Sorry for my English_

**Comment by danielkrupinski** [comment]
The "Fast reload" is only a visual thing - even if animation is shorter game will block you from firing.
