### ISSUE TITLE
Error When injecting cheat

### ISSUE THREAD

**Issue by prop11** [danielkrupinski/GOESP#41]
![image](https://user-images.githubusercontent.com/1337991/86740007-3cd76880-c02e-11ea-9007-45cfab048d14.png)

**Comment by danielkrupinski** [comment]
Have you modified the source code?

**Comment by prop11** [comment]
No the source code is completely unmodified

**Comment by prop11** [comment]
It seems to happen when using Manual Map injection

**Comment by danielkrupinski** [comment]
Try compiling in release configuration.

**Comment by prop11** [comment]
This worked. Thanks
