### ISSUE TITLE
Cheat GUI not showinn up

### ISSUE THREAD

**Issue by JhonnyAndreatta** [danielkrupinski/GOESP#44]
I downloaded the code and compile to generate the DLL, but when I try to inject the DLL with my own DLL injector the hack doesen't show up even when I press INSERT. I'would like to know if is necessary some visual C++ redistributable to run, or my DLL injector isin't working anymore?

**Comment by danielkrupinski** [comment]
The menu pops up right after injection - if you can't see it then your injector is not working.
