### ISSUE TITLE
Font Atlas not built errror

### ISSUE THREAD

**Issue by JhonnyAndreatta** [danielkrupinski/GOESP#45]
When I try to inject the DLL to csgo an message box show up saing that Assertion failed! "Font Atlas not built. It is generally  built by the renderer"
imgui_impl_win32.cpp - Line: 184
![image](https://user-images.githubusercontent.com/53795172/87608569-ae6e8100-c6d6-11ea-94b4-a937b2ba20c9.png)

**Comment by danielkrupinski** [comment]
#41
