### ISSUE TITLE
Error when injected

### ISSUE THREAD

**Issue by finallight1** [danielkrupinski/GOESP#47]
![image](https://user-images.githubusercontent.com/60598537/89128180-76e83d00-d4fc-11ea-8964-bc2f1bc4ad80.png)

**Comment by finallight1** [comment]
By the way, buttons are: Break, Retry, Skip

**Comment by finallight1** [comment]
Compiled with the project settings that were set by the creator of this source and x86 bit

**Comment by danielkrupinski** [comment]
#41

**Comment by finallight1** [comment]
Yeah, saw that already, thx
