### ISSUE TITLE
[Linux] Failure to compile.

### ISSUE THREAD

**Issue by Antiswitcher** [danielkrupinski/GOESP#52]
make -j $(nproc --all)
[  4%] Building CXX object CMakeFiles/GOESP.dir/GOESP/GUI.cpp.o
[  9%] Building CXX object CMakeFiles/GOESP.dir/GOESP/Config.cpp.o
[ 14%] Building CXX object CMakeFiles/GOESP.dir/GOESP/Hacks/ESP.cpp.o
[ 19%] Building CXX object CMakeFiles/GOESP.dir/GOESP/GameData.cpp.o
[ 23%] Building CXX object CMakeFiles/GOESP.dir/GOESP/Hacks/Misc.cpp.o
[ 28%] Building CXX object CMakeFiles/GOESP.dir/GOESP/ImGuiCustom.cpp.o
[ 33%] Building CXX object CMakeFiles/GOESP.dir/GOESP/Helpers.cpp.o
[ 38%] Building CXX object CMakeFiles/GOESP.dir/GOESP/Hooks.cpp.o
In file included from /home/lafont/Desktop/csgo/GOESP-master/GOESP/GUI.cpp:5:0:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Config.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/GOESP.dir/build.make:107: recipe for target 'CMakeFiles/GOESP.dir/GOESP/GUI.cpp.o' failed
make[2]: *** [CMakeFiles/GOESP.dir/GOESP/GUI.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/lafont/Desktop/csgo/GOESP-master/GOESP/Config.cpp:9:0:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Config.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/GOESP.dir/build.make:81: recipe for target 'CMakeFiles/GOESP.dir/GOESP/Config.cpp.o' failed
make[2]: *** [CMakeFiles/GOESP.dir/GOESP/Config.cpp.o] Error 1
In file included from /home/lafont/Desktop/csgo/GOESP-master/GOESP/Hacks/ESP.cpp:8:0:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Hacks/../Config.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/GOESP.dir/build.make:133: recipe for target 'CMakeFiles/GOESP.dir/GOESP/Hacks/ESP.cpp.o' failed
make[2]: *** [CMakeFiles/GOESP.dir/GOESP/Hacks/ESP.cpp.o] Error 1
In file included from /home/lafont/Desktop/csgo/GOESP-master/GOESP/Hacks/Misc.cpp:7:0:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Hacks/../Config.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/GOESP.dir/build.make:146: recipe for target 'CMakeFiles/GOESP.dir/GOESP/Hacks/Misc.cpp.o' failed
make[2]: *** [CMakeFiles/GOESP.dir/GOESP/Hacks/Misc.cpp.o] Error 1
In file included from /home/lafont/Desktop/csgo/GOESP-master/GOESP/Hooks.cpp:3:0:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Config.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/GOESP.dir/build.make:172: recipe for target 'CMakeFiles/GOESP.dir/GOESP/Hooks.cpp.o' failed
make[2]: *** [CMakeFiles/GOESP.dir/GOESP/Hooks.cpp.o] Error 1
In file included from /home/lafont/Desktop/csgo/GOESP-master/GOESP/Helpers.cpp:6:0:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Config.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/GOESP.dir/build.make:159: recipe for target 'CMakeFiles/GOESP.dir/GOESP/Helpers.cpp.o' failed
make[2]: *** [CMakeFiles/GOESP.dir/GOESP/Helpers.cpp.o] Error 1
In file included from /home/lafont/Desktop/csgo/GOESP-master/GOESP/GameData.cpp:8:0:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Config.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/GOESP.dir/build.make:120: recipe for target 'CMakeFiles/GOESP.dir/GOESP/GameData.cpp.o' failed
make[2]: *** [CMakeFiles/GOESP.dir/GOESP/GameData.cpp.o] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/GOESP.dir/all' failed
make[1]: *** [CMakeFiles/GOESP.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Antiswitcher** [comment]
Lubuntu

**Comment by danielkrupinski** [comment]
What's your GCC version?

**Comment by Antiswitcher** [comment]
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by danielkrupinski** [comment]
Update to at least 9.3.0.

**Comment by Antiswitcher** [comment]
I installed gcc 10 and g++ 10, still giving same-ish error 

make -j $(nproc --all)
[  4%] Building CXX object CMakeFiles/GOESP.dir/GOESP/Config.cpp.o
[  9%] Building CXX object CMakeFiles/GOESP.dir/GOESP/GUI.cpp.o
[ 14%] Building CXX object CMakeFiles/GOESP.dir/GOESP/GameData.cpp.o
[ 19%] Building CXX object CMakeFiles/GOESP.dir/GOESP/Hacks/Misc.cpp.o
[ 23%] Building CXX object CMakeFiles/GOESP.dir/GOESP/Hacks/ESP.cpp.o
[ 28%] Building CXX object CMakeFiles/GOESP.dir/GOESP/Hooks.cpp.o
[ 33%] Building CXX object CMakeFiles/GOESP.dir/GOESP/Helpers.cpp.o
[ 38%] Building CXX object CMakeFiles/GOESP.dir/GOESP/Memory.cpp.o
In file included from /home/lafont/Desktop/csgo/GOESP-master/GOESP/Hooks.cpp:3:0:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Config.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
In file included from /home/lafont/Desktop/csgo/GOESP-master/GOESP/Helpers.cpp:6:0:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Config.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
compilation terminated.
CMakeFiles/GOESP.dir/build.make:172: recipe for target 'CMakeFiles/GOESP.dir/GOESP/Hooks.cpp.o' failed
make[2]: *** [CMakeFiles/GOESP.dir/GOESP/Hooks.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/GOESP.dir/build.make:159: recipe for target 'CMakeFiles/GOESP.dir/GOESP/Helpers.cpp.o' failed
make[2]: *** [CMakeFiles/GOESP.dir/GOESP/Helpers.cpp.o] Error 1
In file included from /home/lafont/Desktop/csgo/GOESP-master/GOESP/Config.cpp:9:0:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Config.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/GOESP.dir/build.make:81: recipe for target 'CMakeFiles/GOESP.dir/GOESP/Config.cpp.o' failed
make[2]: *** [CMakeFiles/GOESP.dir/GOESP/Config.cpp.o] Error 1
In file included from /home/lafont/Desktop/csgo/GOESP-master/GOESP/GUI.cpp:5:0:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Config.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/GOESP.dir/build.make:107: recipe for target 'CMakeFiles/GOESP.dir/GOESP/GUI.cpp.o' failed
make[2]: *** [CMakeFiles/GOESP.dir/GOESP/GUI.cpp.o] Error 1
In file included from /home/lafont/Desktop/csgo/GOESP-master/GOESP/GameData.cpp:8:0:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Config.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
In file included from /home/lafont/Desktop/csgo/GOESP-master/GOESP/Hacks/Misc.cpp:7:0:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Hacks/../Config.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
compilation terminated.
In file included from /home/lafont/Desktop/csgo/GOESP-master/GOESP/Hacks/ESP.cpp:8:0:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Hacks/../Config.h:4:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
CMakeFiles/GOESP.dir/build.make:120: recipe for target 'CMakeFiles/GOESP.dir/GOESP/GameData.cpp.o' failed
make[2]: *** [CMakeFiles/GOESP.dir/GOESP/GameData.cpp.o] Error 1
CMakeFiles/GOESP.dir/build.make:146: recipe for target 'CMakeFiles/GOESP.dir/GOESP/Hacks/Misc.cpp.o' failed
make[2]: *** [CMakeFiles/GOESP.dir/GOESP/Hacks/Misc.cpp.o] Error 1
CMakeFiles/GOESP.dir/build.make:133: recipe for target 'CMakeFiles/GOESP.dir/GOESP/Hacks/ESP.cpp.o' failed
make[2]: *** [CMakeFiles/GOESP.dir/GOESP/Hacks/ESP.cpp.o] Error 1
In file included from /home/lafont/Desktop/csgo/GOESP-master/GOESP/Memory.cpp:8:0:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Memory.h: In lambda function:
/home/lafont/Desktop/csgo/GOESP-master/GOESP/Memory.h:76:53: error: ‘class std::basic_string_view<char>’ has no member named ‘ends_with’
             if (std::string_view{ info->dlpi_name }.ends_with(moduleInfo->name)) {
                                                     ^~~~~~~~~
CMakeFiles/GOESP.dir/build.make:198: recipe for target 'CMakeFiles/GOESP.dir/GOESP/Memory.cpp.o' failed
make[2]: *** [CMakeFiles/GOESP.dir/GOESP/Memory.cpp.o] Error 1
CMakeFiles/Makefile2:94: recipe for target 'CMakeFiles/GOESP.dir/all' failed
make[1]: *** [CMakeFiles/GOESP.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by danielkrupinski** [comment]
Make sure CMake uses g++10.

**Comment by Antiswitcher** [comment]
What options should I use to make sure Cmake uses G++10?

**Comment by Antiswitcher** [comment]
oops im dumb. compiled fine, thanks.

**Comment by Antiswitcher** [comment]
How do I inject on linux?

**Comment by Antiswitcher** [comment]
I don't see a compiled file

**Comment by danielkrupinski** [comment]
You can use [load script from Fusion](https://github.com/LWSS/Fuzion/blob/master/load). Binary is located inside Release folder.

**Comment by Antiswitcher** [comment]
I'm not exactly sure how I use this. I have the compiled .so, but it's asking me to download the entire cheat suite of fuzion.

**Comment by danielkrupinski** [comment]
Just edit that script to load your libGOESP.so.
