### ISSUE TITLE
[Linux] Small IMGUI Window

### ISSUE THREAD

**Issue by daggerfella** [danielkrupinski/GOESP#56]
![GOESPIMGUI](https://user-images.githubusercontent.com/42888536/91627529-b5203180-e9c0-11ea-912e-52435ce92055.png)

Used the load script from Fuzion.

**Comment by lbaldim** [comment]
Unable to resize.

**Comment by danielkrupinski** [comment]
Inject having CS:GO in windowed mode + not minimized. I'll try to fix it soon.
