### ISSUE TITLE
Question: Why remove "module caching" on Linux?

### ISSUE THREAD

**Issue by mutexsync** [danielkrupinski/GOESP#59]
I was going to implement module caching in Linux (not iterating with **dl_iterate_phdr** each call) but then I saw the file commit history, and noticed that you already did it once, but removed.

Any specific reason?

**Comment by danielkrupinski** [comment]
No need to as we initialize Memory object only once.

**Comment by mutexsync** [comment]
Oh, makes sense.
Thanks!
