### ISSUE TITLE
problems with the GUI

### ISSUE THREAD

**Issue by Patocx** [danielkrupinski/GOESP#68]
is it possible for me to put an image like a lake inside the menu already injected into the csgo?

**Comment by playday3008** [comment]
https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-can-i-display-an-image-what-is-imtextureid-how-does-it-work

**Comment by Patocx** [comment]
I am new to C ++, but I was able to translate the functions and change the colors, but I am stuck in putting the image, I read the topic and tried even more I couldn't

**Comment by playday3008** [comment]
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples
