### ISSUE TITLE
[Error] Linux Compile

### ISSUE THREAD

**Issue by rafalohaki** [danielkrupinski/GOESP#88]
![image](https://user-images.githubusercontent.com/20607107/105728015-f72bb000-5f2b-11eb-993e-a2cc0aa3fcc1.png)
 my commands:
sudo apt-get install cmake gcc-10 g++-10 libsdl2-dev
mkdir Release
cd Release
cmake -D CMAKE_BUILD_TYPE=Release ..
make -j $(nproc --all)

full output: 
https://0bin.net/paste/+QgUyu5L#raWBNQ+T16J90i2G+qPTxIpQedPufkhsE7d9TqoK+bU

**Comment by rafalohaki** [comment]
`alohaki@Autarch:~/GOESP/Release$ make -j $(nproc --all)
[ 20%] Building CXX object CMakeFiles/GOESP.dir/GOESP/EventListener.cpp.o
[ 20%] Building CXX object CMakeFiles/GOESP.dir/GOESP/Hacks/ESP.cpp.o
[ 20%] Building CXX object CMakeFiles/GOESP.dir/GOESP/GameData.cpp.o
[ 20%] Building CXX object CMakeFiles/GOESP.dir/GOESP/GUI.cpp.o
In file included from /home/rafalohaki/GOESP/GOESP/Hacks/ESP.cpp:15:0:
/home/rafalohaki/GOESP/GOESP/Hacks/../Helpers.h:4:19: fatal error: numbers: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/GOESP.dir/build.make:102: CMakeFiles/GOESP.dir/GOESP/Hacks/ESP.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/rafalohaki/GOESP/GOESP/GUI.cpp:15:0:
/home/rafalohaki/GOESP/GOESP/GUI.h:3:22: fatal error: filesystem: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/GOESP.dir/build.make:76: CMakeFiles/GOESP.dir/GOESP/GUI.cpp.o] Error 1
In file included from /home/rafalohaki/GOESP/GOESP/EventListener.cpp:3:0:
/home/rafalohaki/GOESP/GOESP/EventListener.h:14:39: error: 'eventListener' declared as an 'inline' variable
 inline std::unique_ptr<EventListener> eventListener;
                                       ^
In file included from /home/rafalohaki/GOESP/GOESP/Resources/avatar_ct.h:3:0,
                 from /home/rafalohaki/GOESP/GOESP/GameData.cpp:20:
/home/rafalohaki/GOESP/GOESP/Resources/Resource.h: In lambda function:
/home/rafalohaki/GOESP/GOESP/Resources/Resource.h:12:50: error: expected '{' before 'constexpr'
         constexpr auto decode85Byte = [](char c) constexpr -> unsigned int { return c >= '\\' ? c - 36 : c - 35; };
                                                  ^
/home/rafalohaki/GOESP/GOESP/Resources/Resource.h: In function 'constexpr auto Resource::decodeBase85(const char (&)[N])':
/home/rafalohaki/GOESP/GOESP/Resources/Resource.h:12:50: error: expected ',' or ';' before 'constexpr'
In file included from /home/rafalohaki/GOESP/GOESP/GameData.cpp:20:0:
/home/rafalohaki/GOESP/GOESP/Resources/avatar_ct.h: At global scope:
/home/rafalohaki/GOESP/GOESP/Resources/avatar_ct.h:10:23: error: 'Resource::avatar_ct' declared as an 'inline' variable
 inline constexpr auto avatar_ct = decodeBase85(
                       ^
In file included from /home/rafalohaki/GOESP/GOESP/Resources/avatar_ct.h:3:0,
                 from /home/rafalohaki/GOESP/GOESP/GameData.cpp:20:
/home/rafalohaki/GOESP/GOESP/Resources/Resource.h: In instantiation of 'constexpr auto Resource::decodeBase85(const char (&)[N]) [with long unsigned int N = 1201ul]':
/home/rafalohaki/GOESP/GOESP/Resources/avatar_ct.h:19:83:   required from here
/home/rafalohaki/GOESP/GOESP/Resources/Resource.h:15:165: error: invalid operands of types 'int' and 'void' to binary 'operator*'
             unsigned int tmp = decode85Byte(input[i]) + 85 * (decode85Byte(input[i + 1]) + 85 * (decode85Byte(input[i + 2]) + 85 * (decode85Byte(input[i + 3]) + 85 * decode85Byte(input[i + 4]))));
                                                                                                                                                                     ^
In file included from /home/rafalohaki/GOESP/GOESP/GameData.cpp:20:0:
/home/rafalohaki/GOESP/GOESP/Resources/avatar_ct.h:19:83: error: 'constexpr auto Resource::decodeBase85(const char (&)[N]) [with long unsigned int N = 1201ul]' called in a constant expression
 "oVY5LcuWEt]'=KK=ClX,nqrZ`e:XkH=[[cRYPjeA=8B=WPw:Da0fIT9rcw85e%###Ub90<d$bsAP$###");
                                                                                   ^
In file included from /home/rafalohaki/GOESP/GOESP/Resources/avatar_ct.h:3:0,
                 from /home/rafalohaki/GOESP/GOESP/GameData.cpp:20:
/home/rafalohaki/GOESP/GOESP/Resources/Resource.h:8:20: note: 'constexpr auto Resource::decodeBase85(const char (&)[N]) [with long unsigned int N = 1201ul]' is not usable as a constexpr function because:
     constexpr auto decodeBase85(const char(&input)[N]) noexcept
                    ^
/home/rafalohaki/GOESP/GOESP/Resources/Resource.h:8:20: sorry, unimplemented: unexpected AST of kind loop_expr
/home/rafalohaki/GOESP/GOESP/Resources/Resource.h:8: confused by earlier errors, bailing out
make[2]: *** [CMakeFiles/GOESP.dir/build.make:89: CMakeFiles/GOESP.dir/GOESP/GameData.cpp.o] Error 1
In file included from /home/rafalohaki/GOESP/GOESP/SDK/WeaponInfo.h:3:0,
                 from /home/rafalohaki/GOESP/GOESP/SDK/Entity.h:7,
                 from /home/rafalohaki/GOESP/GOESP/GameData.h:11,
                 from /home/rafalohaki/GOESP/GOESP/EventListener.cpp:5:
/home/rafalohaki/GOESP/GOESP/SDK/Pad.h:10:10: error: 'byte' in namespace 'std' does not name a type
     std::byte PAD_NAME(__COUNTER__) [size]; \
          ^
/home/rafalohaki/GOESP/GOESP/SDK/WeaponInfo.h:26:5: note: in expansion of macro 'PAD'
     PAD(IS_WIN32() ? 20 : 32)
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Pad.h:10:10: error: 'byte' in namespace 'std' does not name a type
     std::byte PAD_NAME(__COUNTER__) [size]; \
          ^
/home/rafalohaki/GOESP/GOESP/SDK/WeaponInfo.h:28:5: note: in expansion of macro 'PAD'
     PAD(IS_WIN32() ? 112 : 204)
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Pad.h:10:10: error: 'byte' in namespace 'std' does not name a type
     std::byte PAD_NAME(__COUNTER__) [size]; \
          ^
/home/rafalohaki/GOESP/GOESP/SDK/WeaponInfo.h:30:5: note: in expansion of macro 'PAD'
     PAD(IS_WIN32() ? 60 : 72)
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Pad.h:10:10: error: 'byte' in namespace 'std' does not name a type
     std::byte PAD_NAME(__COUNTER__) [size]; \
          ^
/home/rafalohaki/GOESP/GOESP/SDK/WeaponInfo.h:32:5: note: in expansion of macro 'PAD'
     PAD(4)
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Pad.h:10:10: error: 'byte' in namespace 'std' does not name a type
     std::byte PAD_NAME(__COUNTER__) [size]; \
          ^
/home/rafalohaki/GOESP/GOESP/SDK/WeaponInfo.h:34:5: note: in expansion of macro 'PAD'
     PAD(IS_WIN32() ? 24 : 28)
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Pad.h:10:10: error: 'byte' in namespace 'std' does not name a type
     std::byte PAD_NAME(__COUNTER__) [size]; \
          ^
/home/rafalohaki/GOESP/GOESP/SDK/WeaponInfo.h:36:5: note: in expansion of macro 'PAD'
     PAD(3)
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Pad.h:10:10: error: 'byte' in namespace 'std' does not name a type
     std::byte PAD_NAME(__COUNTER__) [size]; \
          ^
/home/rafalohaki/GOESP/GOESP/SDK/WeaponInfo.h:41:5: note: in expansion of macro 'PAD'
     PAD(8)
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Pad.h:10:10: error: 'byte' in namespace 'std' does not name a type
     std::byte PAD_NAME(__COUNTER__) [size]; \
          ^
/home/rafalohaki/GOESP/GOESP/SDK/WeaponInfo.h:44:5: note: in expansion of macro 'PAD'
     PAD(16)
     ^
In file included from /home/rafalohaki/GOESP/GOESP/GameData.h:11:0,
                 from /home/rafalohaki/GOESP/GOESP/EventListener.cpp:5:
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:91:5: note: in expansion of macro 'PROP'
     PROP(hitboxSet, WIN32_UNIX(0x9FC, 0xFA8), int)                                 // CBaseAnimating->m_nHitboxSet
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:93:5: note: in expansion of macro 'PROP'
     PROP(weaponId, WIN32_UNIX(0x2FAA, 0x37B2), WeaponId)                           // CBaseAttributableItem->m_iItemDefinitionIndex
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:95:5: note: in expansion of macro 'PROP'
     PROP(clip, WIN32_UNIX(0x3264, 0x3AE4), int)                                    // CBaseCombatWeapon->m_iClip1
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:96:5: note: in expansion of macro 'PROP'
     PROP(isInReload, WIN32_UNIX(0x32A5, 0x3B29), bool)                             // CBaseCombatWeapon->m_bInReload (client-side only)
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:97:5: note: in expansion of macro 'PROP'
     PROP(reserveAmmoCount, WIN32_UNIX(0x326C, 0x3AEC), int)                        // CBaseCombatWeapon->m_iPrimaryReserveAmmoCount
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:98:5: note: in expansion of macro 'PROP'
     PROP(nextPrimaryAttack, WIN32_UNIX(0x3238, 0x3AB8), float)                     // CBaseCombatWeapon->m_flNextPrimaryAttack
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:100:5: note: in expansion of macro 'PROP'
     PROP(prevOwner, WIN32_UNIX(0x3384, 0x3C1C), int)                               // CWeaponCSBase->m_hPrevOwner
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:102:5: note: in expansion of macro 'PROP'
     PROP(ownerEntity, WIN32_UNIX(0x14C, 0x184), int)                               // CBaseEntity->m_hOwnerEntity
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:103:5: note: in expansion of macro 'PROP'
     PROP(spotted, WIN32_UNIX(0x93D, 0xECD), bool)                                  // CBaseEntity->m_bSpotted
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:105:5: note: in expansion of macro 'PROP'
     PROP(thrower, WIN32_UNIX(0x29A0, 0x3040), int)                                 // CBaseGrenade->m_hThrower
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:107:5: note: in expansion of macro 'PROP'
     PROP(fireXDelta, WIN32_UNIX(0x9E4, 0xF80), int[100])                           // CInferno->m_fireXDelta
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:108:5: note: in expansion of macro 'PROP'
     PROP(fireYDelta, WIN32_UNIX(0xB74, 0x1110), int[100])                          // CInferno->m_fireYDelta
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:109:5: note: in expansion of macro 'PROP'
     PROP(fireZDelta, WIN32_UNIX(0xD04, 0x12A0), int[100])                          // CInferno->m_fireZDelta
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:110:5: note: in expansion of macro 'PROP'
     PROP(fireIsBurning, WIN32_UNIX(0xE94, 0x1430), bool[100])                      // CInferno->m_bFireIsBurning
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:111:5: note: in expansion of macro 'PROP'
     PROP(fireCount, WIN32_UNIX(0x13A8, 0x1944), int)                               // CInferno->m_fireCount
     ^
In file included from /home/rafalohaki/GOESP/GOESP/GameData.h:11:0,
                 from /home/rafalohaki/GOESP/GOESP/EventListener.cpp:5:
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:155:47: warning: 'nodiscard' attribute directive ignored [-Wattributes]
     [[nodiscard]] std::string getPlayerName() noexcept;
                                               ^
In file included from /home/rafalohaki/GOESP/GOESP/GameData.h:11:0,
                 from /home/rafalohaki/GOESP/GOESP/EventListener.cpp:5:
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:162:5: note: in expansion of macro 'PROP'
     PROP(fov, WIN32_UNIX(0x31E4, 0x39A8), int)                                     // CBasePlayer->m_iFOV
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:163:5: note: in expansion of macro 'PROP'
     PROP(fovStart, WIN32_UNIX(0x31E8, 0x39AC), int)                                // CBasePlayer->m_iFOVStart
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:164:5: note: in expansion of macro 'PROP'
     PROP(defaultFov, WIN32_UNIX(0x332C, 0x3B14), int)                              // CBasePlayer->m_iDefaultFOV
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:165:5: note: in expansion of macro 'PROP'
     PROP(lastPlaceName, WIN32_UNIX(0x35B4, 0x3DF0), char[18])                      // CBasePlayer->m_szLastPlaceName
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:167:5: note: in expansion of macro 'PROP'
     PROP(isScoped, WIN32_UNIX(0x3928, 0x4228), bool)                               // CCSPlayer->m_bIsScoped
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:168:5: note: in expansion of macro 'PROP'
     PROP(gunGameImmunity, WIN32_UNIX(0x3944, 0x4244), bool)                        // CCSPlayer->m_bGunGameImmunity
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:169:5: note: in expansion of macro 'PROP'
     PROP(flashDuration, WIN32_UNIX(0xA41C, 0xAD4C) - 0x8, float)                   // CCSPlayer->m_flFlashMaxAlpha - 0x8
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:170:5: note: in expansion of macro 'PROP'
     PROP(shotsFired, WIN32_UNIX(0xA390, 0xACC0), int)                              // CCSPlayer->m_iShotsFired
     ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:32:79: warning: 'nodiscard' attribute directive ignored [-Wattributes]
 [[nodiscard]] std::add_lvalue_reference_t<std::add_const_t<type>> func_name() noexcept \
                                                                               ^
/home/rafalohaki/GOESP/GOESP/SDK/Entity.h:171:5: note: in expansion of macro 'PROP'
     PROP(money, WIN32_UNIX(0xB364, 0xBCA8), int)                                   // CCSPlayer->m_iAccount
     ^
In file included from /home/rafalohaki/GOESP/GOESP/EventListener.cpp:5:0:
/home/rafalohaki/GOESP/GOESP/GameData.h:36:14: error: 'scoped_lock' in namespace 'std' does not name a template type
         std::scoped_lock<std::mutex> lock;
              ^
/home/rafalohaki/GOESP/GOESP/GameData.h:37:34: error: 'mutex' declared as an 'inline' field
         static inline std::mutex mutex;
                                  ^
/home/rafalohaki/GOESP/GOESP/GameData.h: In constructor 'GameData::Lock::Lock()':
/home/rafalohaki/GOESP/GOESP/GameData.h:34:27: error: class 'GameData::Lock' does not have any field named 'lock'
         Lock() noexcept : lock{ mutex } {}
                           ^
/home/rafalohaki/GOESP/GOESP/GameData.h: At global scope:
/home/rafalohaki/GOESP/GOESP/GameData.h:73:20: error: enclosing class of constexpr non-static member function 'auto BaseData::operator<(const BaseData&) const' is not a literal type
     constexpr auto operator<(const BaseData& other) const
                    ^
/home/rafalohaki/GOESP/GOESP/GameData.h:70:8: note: 'BaseData' is not literal because:
 struct BaseData {
        ^
/home/rafalohaki/GOESP/GOESP/GameData.h:70:8: note:   'BaseData' is not an aggregate, does not have a trivial default constructor, and has no constexpr constructor that is not a copy or move constructor
/home/rafalohaki/GOESP/GOESP/GameData.h:93:20: error: enclosing class of constexpr non-static member function 'auto ProjectileData::operator==(int) const' is not a literal type
     constexpr auto operator==(int otherHandle) const noexcept
                    ^
/home/rafalohaki/GOESP/GOESP/GameData.h:89:8: note: 'ProjectileData' is not literal because:
 struct ProjectileData : BaseData {
        ^
/home/rafalohaki/GOESP/GOESP/GameData.h:89:8: note:   'ProjectileData' has a non-trivial destructor
In file included from /home/rafalohaki/GOESP/GOESP/Hacks/Misc.h:3:0,
                 from /home/rafalohaki/GOESP/GOESP/EventListener.cpp:6:
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h:10:56: error: array must be initialized with a brace-enclosed initializer
     std::array<float, 4> color{ 1.0f, 1.0f, 1.0f, 1.0f };
                                                        ^
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h:10:56: error: too many initializers for 'std::array<float, 4ul>'
In file included from /home/rafalohaki/GOESP/GOESP/Hacks/Misc.h:3:0,
                 from /home/rafalohaki/GOESP/GOESP/EventListener.cpp:6:
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h:54:69: error: could not convert '<brace-enclosed initializer list>()' from '<brace-enclosed initializer list>' to 'const Color&'
 static void to_json(json& j, const Color& o, const Color& dummy = {})
                                                                     ^
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h: In function 'void read(const json&, const char*, T&)':
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h:97:33: error: expected ')' before ';' token
     if (const auto& val = j[key]; val.type() == Type)
                                 ^
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h:97:35: error: 'val' was not declared in this scope
     if (const auto& val = j[key]; val.type() == Type)
                                   ^
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h: In function 'void read(const json&, const char*, bool&)':
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h:106:33: error: expected ')' before ';' token
     if (const auto& val = j[key]; val.type() == value_t::boolean)
                                 ^
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h:106:35: error: 'val' was not declared in this scope
     if (const auto& val = j[key]; val.type() == value_t::boolean)
                                   ^
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h: In function 'void read(const json&, const char*, std::array<_Tp, _Nm>&)':
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h:116:33: error: expected ')' before ';' token
     if (const auto& val = j[key]; val.type() == value_t::array && val.size() == o.size())
                                 ^
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h:116:35: error: 'val' was not declared in this scope
     if (const auto& val = j[key]; val.type() == value_t::array && val.size() == o.size())
                                   ^
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h:116:89: error: expected ';' before ')' token
     if (const auto& val = j[key]; val.type() == value_t::array && val.size() == o.size())
                                                                                         ^
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h: In function 'void read_number(const json&, const char*, T&)':
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h:126:33: error: expected ')' before ';' token
     if (const auto& val = j[key]; val.is_number())
                                 ^
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h:126:35: error: 'val' was not declared in this scope
     if (const auto& val = j[key]; val.is_number())
                                   ^
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h: In function 'void read_map(const json&, const char*, std::unordered_map<std::__cxx11::basic_string<char>, T>&)':
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h:136:33: error: expected ')' before ';' token
     if (const auto& val = j[key]; val.is_object()) {
                                 ^
/home/rafalohaki/GOESP/GOESP/Hacks/../ConfigStructs.h:136:35: error: 'val' was not declared in this scope
     if (const auto& val = j[key]; val.is_object()) {
                                   ^
In file included from /home/rafalohaki/GOESP/GOESP/EventListener.cpp:7:0:
/home/rafalohaki/GOESP/GOESP/Interfaces.h: At global scope:
/home/rafalohaki/GOESP/GOESP/Interfaces.h:54:42: error: 'interfaces' declared as an 'inline' variable
 inline std::unique_ptr<const Interfaces> interfaces;
                                          ^
/home/rafalohaki/GOESP/GOESP/EventListener.cpp: In member function 'virtual void EventListener::fireGameEvent(GameEvent*)':
/home/rafalohaki/GOESP/GOESP/EventListener.cpp:30:9: warning: attributes at the beginning of statement are ignored [-Wattributes]
         [[fallthrough]];
         ^
make[2]: *** [CMakeFiles/GOESP.dir/build.make:63: CMakeFiles/GOESP.dir/GOESP/EventListener.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/GOESP.dir/all] Error 2
make: *** [Makefile:84: all] Error 2`

**Comment by danielkrupinski** [comment]
Try:
`cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=gcc-10 -D CMAKE_CXX_COMPILER=g++-10 ..`
