### ISSUE TITLE
Issue with make -j $(nproc --all)

### ISSUE THREAD

**Issue by Knekro** [danielkrupinski/GOESP#94]
Hello fellow gamer!

I am having trouble with this last command on my Linux Mint machine. I am not rlly experienced on compiling any code so I do not know of what is happening here. For what I can read, it seems like some files are missing. Take a look.
[https://imgur.com/gOyxTR2](url)
Thanks for your time!

**Comment by danielkrupinski** [comment]
#88

**Comment by Knekro** [comment]
It solve the problem! Thank you so much, but i still have another question.
When the program has finished building, do I need to execute some kind of scrip or something to open the cheat and make it run? Because right now it doesn't work after doing all the steps u write down.

Thanks again for your time!

**Comment by Knekro** [comment]
Okay I did some research and I saw I must inject the .so file in to the CSGO process. Thx again for the help and sorry for the dumb questions!
